apiVersion: v1
kind: Namespace
metadata:
  name: cognexus
  labels:
    app.kubernetes.io/name: cognexus
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
