apiVersion: v1
kind: Service
metadata:
  name: cognexus
  namespace: cognexus
  labels:
    app.kubernetes.io/name: cognexus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cognexus
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
